name: Build and Sign iOS .ipa

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.2'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Download Certificate and Provisioning Profile
      - name: Download Certificate and Provisioning Profile
        run: |
          curl -o certificate.p12 "${{ secrets.CERTIFICATE_URL }}"
          curl -o embedded.mobileprovision "${{ secrets.PROVISIONING_PROFILE_URL }}"
        env:
          CERTIFICATE_URL: ${{ secrets.CERTIFICATE_URL }}
          PROVISIONING_PROFILE_URL: ${{ secrets.PROVISIONING_PROFILE_URL }}

      # Step 5: Import Certificate
      - name: Import Certificate
        run: |
          security import certificate.p12 -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security find-identity -p codesigning -v

      # Step 6: Set up Provisioning Profile
      - name: Set up Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp embedded.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      # Step 7: Build iOS app (signed)
      - name: Build iOS app (signed)
        run: flutter build ios --release --no-codesign
      - name : check entitlements
        run : |
          ls ios/Runner/
      # Step 8: Sign the app with Xcode's codesign
      - name: Sign iOS app
        run: |
          cd build/ios/iphoneos
          codesign -f -s "Apple Distribution: James Oldwoods (N985XLQHFY)" --entitlements ios/Runner/Runner.entitlements Runner.app

      # Step 9: Create IPA Package
      - name: Create IPA Package
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r Runner-signed.ipa Payload
          mv Runner-signed.ipa ../

      # Step 10: Upload Signed IPA as Artifact
      - name: Upload Signed IPA
        uses: actions/upload-artifact@v3
        with:
          name: Runner-signed.ipa
          path: build/ios/Runner-signed.ipa
