name: Build Flutter iOS App and Transfer IPA

on:
  repository_dispatch:
    types: [dispatch-ios]
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      # Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.2'

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Download and configure Provisioning Profile
      - name: Download Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          curl -o ~/Library/MobileDevice/Provisioning\ Profiles/TestIPAPublish_final.mobileprovision \
            ${{ secrets.PROVISIONING_PROFILE_URL }}

      # Download and configure Certificate
      - name: Download Certificate
        run: |
          curl -o certificate.p12 ${{ secrets.CERTIFICATE_URL }}

      - name: Import Certificate
        run: |
          security import certificate.p12 -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign

      # Update ExportOptions.plist
      - name: Update ExportOptions.plist
        run: |
          cat > ios/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.example.wallpapers</key>
                  <string>TestIPAPublish final</string>
              </dict>
              <key>signingStyle</key>
              <string>automatic</string>
              <!-- Specifies the signing certificate for the app -->
              <key>signingCertificate</key>
              <string>iPhone Distribution: James Oldwoods (N985XLQHFY)</string> 
              <key>stripSwiftSymbols</key>
              <true/>
              <key>teamID</key>
              <string>${{ secrets.DEVELOPMENT_TEAM }}</string>
          </dict>
          </plist>
          EOF

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      # Build iOS Archive
      - name: Build iOS Archive
        run: |
          cd ios
          xcodebuild archive \
              -workspace Runner.xcworkspace \
              -scheme Runner \
              -archivePath ./build/Runner.xcarchive \
              CODE_SIGN_STYLE=automatic \
              DEVELOPMENT_TEAM=N985XLQHFY \
              PROVISIONING_PROFILE_SPECIFIER="TestIPAPublish final"

        env:
          FLUTTER_ROOT: ${{ runner.tool_cache }}/flutter

      # Export IPA
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ./ios/build/Runner.xcarchive \
            -exportPath ./ios/build/ipa \
            -exportOptionsPlist ./ios/ExportOptions.plist
        env:
          FLUTTER_ROOT: ${{ runner.tool_cache }}/flutter

      # Upload IPA as artifact
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: ios/build/ipa/Runner.ipa
