name: Build Flutter iOS App and Transfer IPA

on:
  repository_dispatch:
    types: [dispatch-ios]
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      # Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.2'

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Download and configure Provisioning Profile
      - name: Download Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          curl -o ~/Library/MobileDevice/Provisioning\ Profiles/TestIPAPublish_final.mobileprovision \
            ${{ secrets.PROVISIONING_PROFILE_URL }}

      # Download and configure Certificate
      - name: Download Certificate
        run: |
          curl -o certificate.p12 ${{ secrets.CERTIFICATE_URL }}

      # Unlock the Keychain
      - name: Unlock Keychain
        run: |
          security unlock-keychain -p "" ~/Library/Keychains/login.keychain-db
      
      # Import Certificate
      - name: Import Certificate
        run: |
          security import certificate.p12 -P "${{ secrets.CERTIFICATE_PASSWORD }}" \
            -T /usr/bin/codesign -T /usr/bin/security
      
      # Debugging: Check Installed Certificates
      - name: Check Installed Certificates
        run: security find-identity -p codesigning -v
      # Debugging: List Available Provisioning Profiles
      - name: List Provisioning Profiles
        run: ls ~/Library/MobileDevice/Provisioning\ Profiles

      # Update ExportOptions.plist
      - name: Update ExportOptions.plist
        run: |
          cat > ios/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.example.wallpapers</key>
                  <string>TestIPAPublish final</string>
              </dict>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>iPhone Distribution: James Oldwoods (N985XLQHFY)</string> 
              <key>stripSwiftSymbols</key>
              <true/>
              <key>teamID</key>
              <string>N985XLQHFY</string>
          </dict>
          </plist>
          EOF

      # Install CocoaPods
      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      # Build iOS Archive
      - name: Build iOS Archive
        run: |
          cd ios
          xcodebuild archive \
              -workspace Runner.xcworkspace \
              -scheme Runner \
              -archivePath ./build/Runner.xcarchive \
              CODE_SIGN_STYLE=Manual \
              DEVELOPMENT_TEAM=N985XLQHFY \
              PROVISIONING_PROFILE_SPECIFIER="TestIPAPublish final" \
              CODE_SIGN_IDENTITY="Apple Distribution: James Oldwoods (N985XLQHFY)" \
              OTHER_CODE_SIGN_FLAGS="--deep" \
              ONLY_ACTIVE_ARCH=NO

        env:
          FLUTTER_ROOT: ${{ runner.tool_cache }}/flutter

      # Export IPA
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ./ios/build/Runner.xcarchive \
            -exportPath ./ios/build/ipa \
            -exportOptionsPlist ./ios/ExportOptions.plist
        env:
          FLUTTER_ROOT: ${{ runner.tool_cache }}/flutter

      # Upload IPA as artifact
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: ios/build/ipa/Runner.ipa
