name: Build Unsigned iOS .ipa

on:
  push:
    branches:
      - main  # You can adjust this to the branch you want to trigger on
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest  # macOS runner is required for iOS builds

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: '3.24.2'

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS app (unsigned)
      run: flutter build ios --release --no-codesign

    - name: Export unsigned .ipa using xcodebuild
      run: |
        # Set paths to the generated app and the export directory
        APP_PATH="$GITHUB_WORKSPACE/build/ios/iphoneos/Runner.app"
        EXPORT_DIR="$GITHUB_WORKSPACE/build/unsigned-ipa"

        # Create export directory if it doesn't exist
        mkdir -p "$EXPORT_DIR"

        # Create an export options plist (needed for xcodebuild export)
        cat > "$EXPORT_DIR/exportOptions.plist" << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string> <!-- You can use 'ad-hoc', 'development', or 'enterprise' -->
            <key>teamID</key>
            <string>N985XLQHFY</string>  <!-- Replace with your Apple Developer Team ID -->
            <key>compileBitcode</key>
            <false/>
          </dict>
        </plist>
        EOF

        # Export the unsigned .ipa using xcodebuild
        xcodebuild -exportArchive -archivePath "$APP_PATH" \
                    -exportOptionsPlist "$EXPORT_DIR/exportOptions.plist" \
                    -exportPath "$EXPORT_DIR"

    - name: Upload unsigned .ipa as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: unsigned-ipa
        path: $GITHUB_WORKSPACE/build/unsigned-ipa/Runner.ipa
