name: Build Unsigned iOS .ipa

on:
  push:
    branches:
      - main  # You can adjust this to the branch you want to trigger on
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest  # macOS runner is required for iOS builds

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: '3.24.2'

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS app (unsigned)
      run: flutter build ios --release --no-codesign

    - name: Package unsigned .ipa
      run: |
        cd $GITHUB_WORKSPACE/build/ios/iphoneos
        zip -r "$GITHUB_WORKSPACE/build/unsigned-ipa/Runner.ipa" Runner.app

    - name: Upload unsigned .ipa as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: unsigned-ipa
        path: $GITHUB_WORKSPACE/build/unsigned-ipa/Runner.ipa
